# Generated by Django 3.1.2 on 2020-11-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(upload_to='templates/images'),
        ),
    ]
