# Generated by Django 3.1.2 on 2020-11-09 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201108_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='listings',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='comment',
            field=models.ManyToManyField(blank=True, to='auctions.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
