# Generated by Django 3.1.2 on 2020-11-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201108_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='comment', to='auctions.AuctionListing'),
        ),
    ]
