# Generated by Django 3.1.2 on 2020-11-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201118_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='user',
        ),
    ]
