# Generated by Django 3.1.2 on 2020-11-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201118_1831'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='auctionlisting',
    #         name='time_of_listing',
    #     ),
    #     migrations.RemoveField(
    #         model_name='bid',
    #         name='time_of_bid',
    #     ),
    # ]
