# Generated by Django 3.1.2 on 2020-11-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201119_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='time_of_listing',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='time_of_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
