# Generated by Django 3.1.2 on 2020-11-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20201119_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='time_of_bid',
        ),
        migrations.AddField(
            model_name='comment',
            name='time_of_listing',
            field=models.DateTimeField(null=True, auto_now_add=True, blank=True,),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='time_of_listing',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
