# Generated by Django 3.1.2 on 2020-11-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20201124_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='time_of_listing',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='time_of_listing',
        ),
    ]
