# Generated by Django 3.1.2 on 2020-11-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20201124_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time_of_bid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
