# Generated by Django 3.1.2 on 2020-11-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20201125_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
