# Generated by Django 3.1.2 on 2020-11-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20201125_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
