# Generated by Django 3.1.2 on 2020-11-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_auto_20201129_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(blank=True, default='images/no-image.jpg', upload_to='auctions/images/'),
        ),
    ]
